version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: symfony-docker
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret